# alacritty终端配置
# MacPath: ${HOME}/.config/alacritty/alacritty.toml
# LinuxPath: ${HOME}/.config/alacritty/alacritty.toml

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
LANG = "en_US.UTF-8"

[window]
decorations = "none"
opacity = 0.8
option_as_alt = "Both"

[font]
size = 18
normal = { family = "SauceCodePro NFM", style = "Regular" }
bold = { family = "SauceCodePro NFM", style = "Bold" }
italic = { family = "SauceCodePro NFM", style = "Italic" }
bold_italic = { family = "SauceCodePro NFM", style = "Bold Italic" }

[cursor]
style = { shape = "Beam", blinking = "Always" }

[colors.primary]
background = "#282828"
foreground = "#dfbf8e"

[colors.normal]
black = "#665c54"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#dfbf8e"
yellow = "#e78a4e"

[colors.bright]
black = "#928374"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#dfbf8e"
yellow = "#e3a84e"
